### ISSUE TITLE
Errorfill transparency is set to 1 when saved to EPS

### ISSUE THREAD

**Issue by amichaut** [tonysyu/mpltools#27]
Saving an errorfill plot to eps does not keep the transparency of the error region. Look at the difference between a plot saved to png:
![test](https://cloud.githubusercontent.com/assets/11176618/6352595/21fd28c2-bc44-11e4-9d7b-d8c37602d466.png)
and to eps:
![test](https://cloud.githubusercontent.com/assets/11176618/6352639/5f1d4930-bc44-11e4-92b6-e1bfc3958eac.png)

**Comment by tonysyu** [comment]
Thanks for reporting, but this is not really an issue with mpltools since eps doesn't support transparency. See the following StackOverflow post:

http://stackoverflow.com/questions/19638773/matplotlib-plots-lose-transparency-when-saving-as-ps-eps
